### PR TITLE
DO NOT MERGE - PHP coding style

### PR DESCRIPTION
**Pull request by austinsmorris**
Open for discussion!  Would like to agree on some things that go beyond psr-2....

### CODE REVIEW

**Comment by mrkrstphr** [comment]
:+1:

**Comment by ryanplasma** [comment]
:+1:

**Comment by austinsmorris** [comment]
@djheru @csamuelson, thoughts?

**Comment by austinsmorris** [comment]
@csamuelson @djheru @joshjwalker, please comment.  something about disagreeing and silence.  so i'll merge this tomorrow.....

**Comment by mrkrstphr** [comment]
It is law.

**Pull request merged**
